services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nats:
    image: nats:2.9
    ports:
      - "4222:4222"
      - "8222:8222"

  orchestrator:
    build: ../services/micro7-orchestrator
    container_name: micro7-orchestrator
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - nats
    environment:
      REDIS_HOST: redis
      NATS_HOST: nats

    


  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microlearn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  datapreparer:
    build: ../services/micro1-data_preparer
    container_name: micro1-datapreparer
    ports:
      - "8000:8000"
    depends_on:
      - nats
      - minio
    environment:
      # Service config
      SERVICE_NAME: DataPreparer
      SERVICE_PORT: 8000

      # NATS (event bus)
      NATS_HOST: nats
      NATS_PORT: 4222

      # MinIO (dataset storage)
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: data-preparer

  model-selector:
    build: ../services/micro2-model_selector
    container_name: micro2-model-selector
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - minio
      - nats
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microlearn
      
      NATS_HOST: nats
      NATS_PORT: 4222

      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: data-preparer

  trainer:
    build: ../services/micro3-trainer
    container_name: micro3-trainer
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - minio
    environment:
      SERVICE_NAME: Trainer
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8002
      DEBUG: "false"

      # PostgreSQL
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microlearn

      # MinIO
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: data-preparer

volumes:
  postgres_data:
  minio_data: